"""fovorite_color changed to favorite_color

Revision ID: cafcc35e1cb2
Revises: b0f6349a1348
Create Date: 2021-12-31 01:25:42.035458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cafcc35e1cb2'
down_revision = 'b0f6349a1348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.String(length=120), nullable=True))
    op.drop_column('users', 'fovorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fovorite_color', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###
